### ISSUE TITLE
Message is cropped when contains date between square brackets

### ISSUE THREAD

**Issue by jdrouet** [StephenWakely/syslog-loose#11]
When parsing `<131>Jun 8 11:54:08 master apache_error [Tue Jun 08 11:54:08.929301 2021] [php7:emerg] [pid 1374899] [client 95.223.77.60:41888] rest of message` it gives the following result:
```
{"appname":"apache_error","facility":"local0","host":"master","hostname":"master","message":"[php7:emerg] [pid 1374899] [client 95.223.77.60:41888] rest of message","severity":"err","source_ip":"127.0.0.1","source_type":"syslog","timestamp":"2021-06-08T18:54:08Z"}
```

The `[Tue Jun 08 11:54:08.929301 2021]` part of the message is dropped.

Comes from [this issue](https://github.com/timberio/vector/issues/7796).

**Comment by StephenWakely** [comment]
I presume it is thinking that this is structured data, but then sees that it is invalid. Currently invalid structured data is being dropped, but thinking about it it does make more sense to include any invalid structured data in the message.

That would impact this [test](https://github.com/StephenWakely/syslog-loose/blob/master/tests/tests.rs#L183-L204) so the `msg` field would actually be:

```rust
 msg: "[software=\"rsyslogd\" swVersion=\"8.32.0\" x-pid=\"20506\" x-info=\"http://www.rsyslog.com\"]  start",
```

I see you have a PR coming up, is that the approach you are taking?

**Comment by jdrouet** [comment]
@StephenWakely it's exactly the approach I'm taking 😉 Thank you for the hint.
