### ISSUE TITLE
Allow for non-FixedOffset time zones

### ISSUE THREAD

**Issue by bruceg** [StephenWakely/syslog-loose#9]
The `parse_message_with_year_tz` function allows for specifying a time zone for parsing timestamps that do not have an explicit zone. The `tz` parameter only allows for `FixedOffset` type zones, which does not allow anything in the `chrono-tz` crate to be used. Instead, it should should be generic on the `TimeZone` trait.

Ref #3

**Comment by StephenWakely** [comment]
This was fixed by #15.
